# Generated by Django 5.1.2 on 2024-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year_of_production', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новый автомобиль')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('transmission', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая')], max_length=20, verbose_name='Коробка передач')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
