# Generated by Django 5.1.2 on 2024-10-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=17, unique=True, verbose_name='VIN-код')),
                ('pts_number', models.CharField(max_length=15, unique=True, verbose_name='Паспорт ТС (ПТС)')),
                ('reg_number', models.CharField(max_length=10, unique=True, verbose_name='Номер автомобиля')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('owner_name', models.CharField(max_length=100, verbose_name='ФИО владельца')),
            ],
            options={
                'verbose_name': 'Документация автомобиля',
                'verbose_name_plural': 'Документация автомобилей',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.vehicledocumentation', verbose_name='Документация'),
        ),
    ]
