# Generated by Django 5.1.2 on 2024-10-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_vehicledocumentation_vehicle_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_new',
        ),
    ]
