# Generated by Django 5.1.2 on 2024-10-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_vehicle_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Модель')),
                ('vehicle_type', models.CharField(choices=[('passenger', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('unmanned', 'Беспилотный'), ('motorcycle', 'Мотоцикл')], max_length=20, verbose_name='Тип транспорта')),
                ('power_capacity', models.PositiveIntegerField(verbose_name='Мощность автомобиля')),
                ('fuel_capacity', models.PositiveIntegerField(verbose_name='Ёмкость бака (л)')),
                ('payload_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъёмность (кг)')),
                ('seating_capacity', models.PositiveIntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cars.model', verbose_name='Модель'),
        ),
    ]
