# Generated by Django 5.1.2 on 2024-10-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_model_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='documentation',
            field=models.OneToOneField(blank=True, default='Не указаны', null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.vehicledocumentation', verbose_name='Документация'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, default='Неизвестная модель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cars.model', verbose_name='Модель'),
        ),
    ]
