# Generated by Django 5.1.2 on 2024-10-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_vehicle_documentation_alter_vehicle_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.vehicledocumentation', verbose_name='Документация'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cars.model', verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enterprise'),
        ),
    ]
