# Generated by Django 5.1.2 on 2024-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_driver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
