# Generated by Django 5.1.2 on 2024-10-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_driver_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.CreateModel(
            name='CarDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(related_name='cars', through='cars.CarDriver', to='cars.vehicle'),
        ),
    ]
