# Generated by Django 5.1.2 on 2024-10-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_driver_car_cardriver_driver_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enterprise', verbose_name='Предприятие'),
        ),
    ]
