# Generated by Django 5.1.2 on 2024-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_driver_cars_vehicledriver_vehicle_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vehicledriver',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный водитель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='cars.VehicleDriver', to='cars.driver'),
        ),
    ]
