# Generated by Django 5.1.2 on 2024-10-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_driver_is_active_vehicledriver_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together={('vehicle', 'driver')},
        ),
    ]
