# Generated by Django 5.1.2 on 2024-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_vehicledriver_driver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vehicledriver',
            constraint=models.UniqueConstraint(fields=('vehicle', 'driver'), name='unique_vehicle_driver'),
        ),
    ]
