# Generated by Django 5.1.2 on 2024-10-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_vehicledriver_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicledriver',
            name='unique_vehicle_driver',
        ),
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together={('vehicle', 'driver')},
        ),
    ]
