# Generated by Django 5.1.2 on 2024-10-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_vehicledriver_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='cars.enterprise', verbose_name='Предприятие'),
        ),
    ]
