# Generated by Django 5.1.2 on 2024-10-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_vehicle_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledriver',
            name='is_active',
        ),
    ]
