# Generated by Django 5.1.2 on 2024-10-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_remove_vehicledriver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='cars.driver', verbose_name='Активный водитель'),
        ),
    ]
