# Generated by Django 5.1.2 on 2024-10-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_vehicle_active_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='cars.driver', verbose_name='Активный водитель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='cars.enterprise', verbose_name='Предприятие'),
        ),
    ]
