# Generated by Django 5.1.2 on 2024-11-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_manager_options_alter_manager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='salary',
            field=models.PositiveIntegerField(null=True, default=0, verbose_name='Зарплата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='cars.driver', verbose_name='Активный водитель'),
        ),
    ]
