# Generated by Django 5.1.2 on 2024-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_manager_salary_alter_vehicle_active_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='salary',
        ),
    ]
