# Generated by Django 5.1.2 on 2024-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_remove_manager_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='height',
            field=models.PositiveIntegerField(null=True, default=0, verbose_name='Высота'),
            preserve_default=False,
        ),
    ]
