# Generated by Django 5.1.2 on 2024-11-12 12:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_driver_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='height',
            field=models.PositiveIntegerField(null=True),  # Позволяет NULL значения

        ),
        migrations.AddField(
            model_name='manager',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
            preserve_default=False,
        ),
    ]
