# Generated by Django 5.1.2 on 2024-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_remove_driver_height_manager_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
        ),
    ]
