# Generated by Django 5.1.2 on 2024-11-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_alter_manager_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='height',
        ),
    ]
