# Generated by Django 5.1.2 on 2024-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_remove_manager_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
