# Generated by Django 5.1.2 on 2024-11-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_manager_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='age',
        ),
    ]
