# Generated by Django 5.1.2 on 2024-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_remove_manager_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
        ),
    ]
