# Generated by Django 5.1.2 on 2024-11-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_driver_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='height',
        ),
    ]
