# Generated by Django 5.1.2 on 2024-11-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0034_remove_driver_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cars.model', verbose_name='Модель автомобиля'),
        ),
    ]
