# Generated by Django 5.1.2 on 2024-12-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0037_rename_purchase_datetime_vehicle_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='purchase_date',
            new_name='purchase_datetime',
        ),
    ]
