# Generated by Django 5.2 on 2025-11-03 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('receive_vehicle_notifications', models.BooleanField(default=True, verbose_name='Уведомления об автомобилях')),
                ('receive_driver_notifications', models.BooleanField(default=True, verbose_name='Уведомления о водителях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Телеграм профиль менеджера',
                'verbose_name_plural': 'Телеграм профили менеджеров',
            },
        ),
    ]
